# Generated by Django 5.1.6 on 2025-02-12 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password_hash", models.CharField(max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="User",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Virtuals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=32)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("rdp", "RDP"), ("ssh", "SSH"), ("vnc", "VNC")],
                        max_length=5,
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                ("port", models.IntegerField()),
                ("user_vm", models.CharField(max_length=64)),
                ("password_vm", models.CharField(max_length=128)),
                ("ignore_cert", models.BooleanField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.user"
                    ),
                ),
            ],
        ),
    ]
